name: Run ADO to GitHub Sync with PowerShell

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-Latest
    steps:
      - name: Check out repository        
        uses: actions/checkout@v3
      - run: |
           
             .\SyncADOtoGitHub.ps1 -GitHubDestinationPAT ${{ secrets.GITHUBDESTINATIONPAT }} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT }}
